version: '2'
services:
  concoursfonctionpublique-app:
    image: concoursfonctionpublique
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=prod,swagger
      - MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED=true
      - SPRING_DATASOURCE_URL=jdbc:postgresql://concoursfonctionpublique-postgresql:5432/concoursFonctionPublique
      - JHIPSTER_SLEEP=30 # gives time for other services to boot before the application
    ports:
      - 8080:8080
  concoursfonctionpublique-postgresql:
    extends:
      file: postgresql.yml
      service: concoursfonctionpublique-postgresql
